IMAGE_CHANNELS = 3
GENERATE_RESOLUTION_FACTOR = 3
GENERATE_SQUARE = 32 * GENERATE_RESOLUTION_FACTOR

PREVIEW_ROWS, PREVIEW_COLS = 4, 7
PREVIEW_MARGIN = 16

SEED_SIZE = 256 #100

DATA_PATH = ''
FOLDER_NAME = 'cartoonset10k'

EPOCHS = 50
BATCH_SIZE = 32 #64
BUFFER_SIZE = 61000